from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
LIT = ROOT / "literature"


TITLE_OLD = "EEG-CogAgent: An Auditable Language-Model Agent for Reproducible Dementia EEG Biomarker Analysis"
TITLE_NEW = "EEG-CogAgent: An Auditable Language-Model-Assisted Workflow for Reproducible Dementia EEG Biomarker Discovery"


RELATED_WORK = """### 1.1 Related work and methodological gap

Several recent methods reduce manual effort in EEG analysis, but they address different parts of the workflow. EEG-AI, a Journal of Neuroscience Methods article, focuses on semi-automated preprocessing, ICA-based artifact classification, closed-loop reruns and human expert oversight [18]. EEG Agent demonstrates that large language models can orchestrate EEG tools and generate reports in a general analysis setting [8]. EEGUnity targets EEG dataset harmonization for large-scale model development [9]. DISCOVER-EEG provides a fully automated biomarker extraction pipeline for clinical neuroscience [7]. In parallel, ds004504 has already been used for AD/FTD/HC classification and multidimensional EEG characterization [11-14].

These studies establish that automated EEG preprocessing, LLM-based EEG tool orchestration, dataset harmonization and dementia EEG classification are active areas. The methodological gap addressed here is narrower: a dementia-focused, auditable BIDS-to-biomarker-to-report workflow that constrains the language-model layer to planning, artifact checking and narrative synthesis while deterministic Python modules produce all numerical results. EEG-CogAgent is therefore not positioned as a preprocessing agent, a generic EEG chatbot or an autonomous diagnostic system. It is a reproducible research workflow for converting open dementia EEG datasets into inspectable biomarker statistics, validation artifacts, figures and claim-bounded reports.
"""


AUDIT_SECTION = """### 2.2 Agent boundary and audit contract

EEG-CogAgent was implemented with a strict boundary between language-model orchestration and numerical EEG analysis. The language model did not inspect raw EEG traces for diagnosis, did not alter numerical outputs, did not relax thresholds after observing results and did not issue participant-level clinical decisions. Its permitted role was to translate a YAML analysis contract into a workflow plan, select authorized deterministic modules, check whether required artifacts were produced and draft constrained narrative text from completed outputs.

All numerical results were generated by deterministic Python modules. The audit contract produced machine-readable JSON and Markdown reports and checked participant uniqueness, expected cohort counts, finite feature matrices, valid metric ranges, complete out-of-fold predictions, probability bounds, failed-participant records and the presence of prespecified figures, statistics, prediction tables and quality-control files. The primary run contained 22 deterministic checks. In this design, the report is subordinate to the artifacts: a claim may appear in the narrative only if it is supported by an inspectable table, figure, audit file or configuration record.
"""


POSITIONING_TABLE = """# Table. Positioning of EEG-CogAgent relative to recent EEG automation and dementia EEG studies

| Study/tool | Primary EEG task | LLM/agent role | Disease validation | Audit/report generation | Boundary relative to EEG-CogAgent |
|---|---|---|---|---|---|
| EEG-AI | Semi-automated preprocessing, ICA artifact removal and rerun decisions | Agentic support for artifact classification and human-in-the-loop review | Not dementia-specific | Closed-loop preprocessing policy; expert oversight | Closest JNM precedent, but focused on artifact removal rather than biomarker discovery or disease-report generation |
| EEG Agent | General automated EEG analysis using LLM tool orchestration | Broad LLM coordinator for EEG tools and reports | Not dementia-specific | General reporting | Establishes LLM EEG orchestration; EEG-CogAgent narrows this to auditable dementia BIDS-to-biomarker validation |
| EEGUnity | Unified EEG dataset preparation for large-scale EEG models | Primarily data harmonization infrastructure | Not dementia-specific | Dataset standardization rather than report audit | Supports upstream harmonization; EEG-CogAgent sits downstream for disease-analysis artifacts |
| DISCOVER-EEG | Fully automated resting-state EEG biomarker extraction | No LLM orchestration | Clinical neuroscience biomarker pipeline | Automated outputs but not LLM report boundary | Demonstrates deterministic biomarker automation; EEG-CogAgent adds constrained planning, audit and report synthesis |
| ds004504 classification studies | AD/FTD/HC EEG classification and multidimensional biomarkers | No LLM/agent role | Direct dementia EEG validation | Usually no explicit audit/report workflow | Shows classification alone is not novel; EEG-CogAgent contributes auditability and claim-bounded reporting |
| EEG-CogAgent | Dementia-focused BIDS-to-biomarker-to-report workflow | Constrained planning, artifact checking and narrative synthesis only | AD/FTD/HC OpenNeuro case study with paired condition-transfer test | JSON/Markdown audit, artifact manifest, figures, tables and constrained report | Research workflow, not autonomous diagnosis or state-of-the-art classifier |
"""


HIGHLIGHTS = """# Highlights

- EEG-CogAgent provides an auditable BIDS-to-biomarker workflow for dementia EEG research.
- Deterministic Python modules generate numerical results; the language-model layer only plans, checks and drafts.
- OpenNeuro AD/FTD/HC validation recovered interpretable slowing-related EEG biomarkers.
- Three-class classification was moderate and AD-versus-FTD separation remained weak.
- The workflow reports negative validation boundaries instead of producing autonomous diagnostic claims.
"""


COVER_LETTER = """# Cover letter draft

Dear Editor,

We are pleased to submit our manuscript, **"EEG-CogAgent: An Auditable Language-Model-Assisted Workflow for Reproducible Dementia EEG Biomarker Discovery,"** for consideration in *Journal of Neuroscience Methods*.

This manuscript describes a methods-focused workflow for reproducible EEG biomarker research. EEG-CogAgent combines BIDS-formatted EEG input, deterministic MNE-Python-based analysis modules, machine-readable audit checks, visualization and constrained report drafting. The language-model layer is deliberately restricted to workflow planning, authorized tool selection, artifact checking and narrative synthesis; it does not inspect raw EEG for diagnosis, change numerical outputs or issue participant-level clinical decisions.

We validated the workflow using an open dementia EEG cohort containing participants with Alzheimer's disease, frontotemporal dementia and healthy controls. The case study recovered interpretable slowing-related biomarkers and disease-versus-control separation, while also exposing important limitations: weak AD-versus-FTD separation, low FTD recall and the absence of independent external validation. We view this claim discipline as central to the method, because the audit contract prevents a language-model report from exceeding the evidence contained in deterministic artifacts.

The work differs from recent EEG automation studies in several ways. EEG-AI focuses on agent-assisted preprocessing and ICA artifact removal; EEG Agent demonstrates general LLM-based EEG tool orchestration; DISCOVER-EEG provides deterministic biomarker extraction; and existing ds004504 studies focus on dementia classification. EEG-CogAgent addresses the narrower methodological gap of an auditable dementia-focused BIDS-to-biomarker-to-report workflow.

We believe the manuscript fits *Journal of Neuroscience Methods* because it presents a reproducible analysis method, validates it on public EEG data, defines explicit safety and audit boundaries for language-model-assisted neuroscience workflows and provides reusable artifacts for future methodological comparison.

The manuscript is original, is not under consideration elsewhere and all authors have approved its submission. Conflicts of interest and funding statements should be completed in the final submission forms.

Sincerely,

[Corresponding author name]
"""


GRAPHICAL_ABSTRACT_TEXT = """# Graphical abstract text

Suggested graphical abstract concept:

**Input:** BIDS-formatted dementia EEG dataset plus YAML analysis contract.

**Constrained LLM layer:** plans authorized tools, checks required artifacts and drafts claim-bounded report text.

**Deterministic EEG modules:** MNE preprocessing, spectral features, connectivity features, graph metrics, statistical testing, nested cross-validation and visualization.

**Audit layer:** verifies participant counts, leakage-safe predictions, metric ranges, probability bounds, failed participants, output completeness and artifact provenance.

**Output:** reproducible biomarker tables, topographic maps, ROC curves, condition-transfer results and manuscript-ready text.

Required visual label:

> The LLM never diagnoses participants and never alters numerical outputs.
"""


CHECKLIST = """# JNM submission checklist

## Manuscript files

- [ ] `docs/FULL_MANUSCRIPT_JNM.md` reviewed by corresponding author
- [ ] JNM-formatted DOCX generated after content freeze
- [ ] Figures exported as high-resolution image files
- [ ] Supplementary table package prepared

## Required scientific checks

- [ ] Title avoids autonomous diagnosis claims
- [ ] Abstract states LLM boundary
- [ ] Related work differentiates EEG-AI, EEG Agent, EEGUnity, DISCOVER-EEG and ds004504 classifiers
- [ ] Methods include Agent boundary and audit contract
- [ ] Results preserve weak AD-vs-FTD and low FTD recall
- [ ] ds006036 described as paired condition transfer, not external validation
- [ ] Limitations include single-site cohort, sample size, confounding and absence of manual-vs-agent comparison

## Elsevier-style submission items

- [ ] Highlights
- [ ] Cover letter
- [ ] Declaration of competing interest
- [ ] Data availability statement
- [ ] Code availability statement
- [ ] Funding statement
- [ ] Author contributions
- [ ] Graphical abstract file or graphical abstract text

## Human placeholders

- [ ] Author names
- [ ] Affiliations
- [ ] Corresponding author email
- [ ] Funding details
- [ ] CRediT author roles
- [ ] Repository URL and release DOI
"""


def insert_after_intro(text: str) -> str:
    marker = "We developed EEG-CogAgent as a constrained orchestration layer for reproducible dementia EEG analysis (Fig. 1)."
    if RELATED_WORK.strip() in text:
        return text
    idx = text.find(marker)
    if idx == -1:
        return text
    return text[:idx] + RELATED_WORK + "\n" + text[idx:]


def insert_audit_section(text: str) -> str:
    if "### 2.2 Agent boundary and audit contract" in text:
        return text
    marker = "### 2.2 Participants and datasets"
    if marker not in text:
        return text
    text = text.replace(marker, AUDIT_SECTION + "\n" + marker)
    # Renumber following 2.x method sections to avoid duplicate 2.2.
    replacements = [
        ("### 2.2 Participants and datasets", "### 2.3 Participants and datasets"),
        ("### 2.3 Preprocessing", "### 2.4 Preprocessing"),
        ("### 2.4 Spectral features", "### 2.5 Spectral features"),
        ("### 2.5 Connectivity and graph features", "### 2.6 Connectivity and graph features"),
        ("### 2.6 Statistical analysis", "### 2.7 Statistical analysis"),
        ("### 2.7 Machine learning", "### 2.8 Machine learning"),
        ("### 2.8 Outputs and reproducibility", "### 2.9 Outputs and reproducibility"),
    ]
    for old, new in replacements:
        text = text.replace(old, new)
    return text


def strengthen_title_and_abstract(text: str) -> str:
    text = text.replace(TITLE_OLD, TITLE_NEW)
    text = text.replace(
        "We developed EEG-CogAgent, a configuration-driven agent that orchestrates deterministic Python modules",
        "We developed EEG-CogAgent, a configuration-driven language-model-assisted workflow that orchestrates deterministic Python modules",
    )
    text = text.replace(
        "EEG-CogAgent links language-model orchestration to auditable EEG analysis",
        "EEG-CogAgent links constrained language-model orchestration to auditable dementia EEG biomarker discovery",
    )
    return text


def main() -> None:
    src = DOCS / "FULL_MANUSCRIPT.md"
    text = src.read_text(encoding="utf-8")
    text = strengthen_title_and_abstract(text)
    text = insert_after_intro(text)
    text = insert_audit_section(text)
    if "EEG-AI: An agentic system for AI-assisted semi-automated EEG preprocessing and artifact removal" not in text:
        text = text.replace(
            "17. Rubinov M, Sporns O. Complex network measures of brain connectivity: uses and interpretations. *NeuroImage*. 2010;52:1059–1069. doi:10.1016/j.neuroimage.2009.10.003.",
            "17. Rubinov M, Sporns O. Complex network measures of brain connectivity: uses and interpretations. *NeuroImage*. 2010;52:1059–1069. doi:10.1016/j.neuroimage.2009.10.003.\n18. Abdou A, Ivanov M, Shaya S, et al. EEG-AI: An agentic system for AI-assisted semi-automated EEG preprocessing and artifact removal. *Journal of Neuroscience Methods*. 2026;110759. doi:10.1016/j.jneumeth.2026.110759.",
        )

    # Add a short pointer to the positioning table after Methods introduction if possible.
    table_note = (
        "\nThe methodological position of EEG-CogAgent relative to recent EEG automation and dementia EEG studies is summarized in Table S1.\n"
    )
    if table_note.strip() not in text:
        text = text.replace("The execution policy was audit first.", table_note + "\nThe execution policy was audit first.")
    text = text.replace(
        "**Figure 1. EEG-CogAgent workflow.** The framework converts a BIDS EEG dataset and YAML configuration into preprocessing, spectral features, connectivity and graph features, statistical analyses, machine-learning validation, audit artifacts and a constrained report draft. The language-model layer coordinates allowed tools and summarizes completed artifacts but does not diagnose participants or modify numerical results.",
        "**Figure 1. Constrained EEG-CogAgent workflow for Journal of Neuroscience Methods submission.** BIDS EEG data and a YAML analysis contract enter deterministic MNE-Python-based modules for preprocessing, biomarker feature extraction, statistical testing, machine-learning validation and research outputs. The language-model layer plans authorized tools, checks required artifacts and drafts claim-bounded text, but never diagnoses participants or alters numerical outputs. The audit contract records participant uniqueness, leakage-safe predictions, probability bounds, artifact manifests and research-only claim boundaries.",
    )
    text = text.replace(
        "**Figure 1. EEG-CogAgent workflow.** A YAML research contract guides BIDS ingestion, deterministic preprocessing and feature extraction, statistical and machine-learning modules, visual outputs, artifact audit, and LLM-assisted report drafting. Numerical modules, audit checks, and narrative generation are separated to prevent the language model from altering results.",
        "**Figure 1. Constrained EEG-CogAgent workflow for Journal of Neuroscience Methods submission.** BIDS EEG data and a YAML analysis contract enter deterministic MNE-Python-based modules for preprocessing, biomarker feature extraction, statistical testing, machine-learning validation and research outputs. The language-model layer plans authorized tools, checks required artifacts and drafts claim-bounded text, but never diagnoses participants or alters numerical outputs. The audit contract records participant uniqueness, leakage-safe predictions, probability bounds, artifact manifests and research-only claim boundaries.",
    )

    (DOCS / "FULL_MANUSCRIPT_JNM.md").write_text(text, encoding="utf-8")
    (DOCS / "TABLE_JNM_POSITIONING.md").write_text(POSITIONING_TABLE, encoding="utf-8")
    (DOCS / "JNM_HIGHLIGHTS.md").write_text(HIGHLIGHTS, encoding="utf-8")
    (DOCS / "JNM_COVER_LETTER.md").write_text(COVER_LETTER, encoding="utf-8")
    (DOCS / "JNM_GRAPHICAL_ABSTRACT_TEXT.md").write_text(GRAPHICAL_ABSTRACT_TEXT, encoding="utf-8")
    (DOCS / "JNM_SUBMISSION_CHECKLIST.md").write_text(CHECKLIST, encoding="utf-8")

    for name in [
        "FULL_MANUSCRIPT_JNM.md",
        "TABLE_JNM_POSITIONING.md",
        "JNM_HIGHLIGHTS.md",
        "JNM_COVER_LETTER.md",
        "JNM_GRAPHICAL_ABSTRACT_TEXT.md",
        "JNM_SUBMISSION_CHECKLIST.md",
    ]:
        print(DOCS / name)


if __name__ == "__main__":
    main()
